version: '3'
services:
        icecast:
                image: danielm1999/icecast2
                environment:
                        - IC_ADMIN=daniel
                        - IC_PASSWORDADMIN=hackme
                        - IC_CLIENTES=100
                        - IC_SOURCES=42
                        - IC_QUEUESIZE=524288
                        - IC_CLITIMEOUT=30
                        - IC_HEADERTIMEOUT=15
                        - IC_SOURCETIMEOUT=10
                        - IC_BURSTCONNECT=1
                        - IC_BURSTSIZE=65535
                        - IC_IP=localhost
                        - IC_PORT=8000
                ports:
                        - "8000:8000"
        https-portal:
                image: steveltn/https-portal:1
                ports:
                        - '80:80'
                        - '443':'443'
                links:
                        - danielm1999/icecast2
                restart: aways
                environment:
                        DOMAINS: 'icecast.sistemaplug.com -> http://icecast.sistemaplug.com:80'
                        STAGE: production
